[package]
name = "maze-solver"
version = "0.1.0"
edition = "2021"

[dependencies.rand]
version = "0.8.5"

[dependencies.sdl2]
version = "*"
features = ["image"]

[dependencies.union-find]
version = "0.4.3"